# Generated by Django 3.2.25 on 2025-05-29 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_installed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCustomField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=20)),
                ('value', models.TextField()),
                ('field_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.customfield')),
                ('module_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.module')),
            ],
        ),
    ]
